// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://honakekyzqlbccujtzxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbmFrZWt5enFsYmNjdWp0enhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTc0NTQsImV4cCI6MjA3NDI5MzQ1NH0.QUfE9P0l-LC5yBn5cyktVNv75e6BpcYmLNtdnuxDr_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});